name: Build macOS Release

on:
  push:
    branches: [ master ]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install Fyne CLI
      run: go install fyne.io/tools/cmd/fyne@latest

    - name: Build macOS App
      run: |
        fyne build --os darwin

    - name: Pack to Zip
      run: |
        zip -r vas_mac.zip vas*

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vas-macOS
        path: vas_mac.zip